### ISSUE TITLE
raw count matrix

### ISSUE THREAD

**Issue by qianxu05172019** [skannan4/cm-dysregulation#1]
Hi,
It seems that the gene_mult.mtx does not contain the raw counts. They are normalized counts instead. Could you provide the raw count matrix without normalization?

**Comment by skannan4** [comment]
Hi! The output should be the direct output from kallisto|bustools; however, I used the -m flag from bustools counts to count multimappers. kb does this fractionally, which is why you'll get fractional counts. But these are still what you would consider raw counts - not normalised.

**Comment by qianxu05172019** [comment]
Got you. Thanks!
